# Generated by Django 5.0.4 on 2024-04-10 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bloco', models.IntegerField()),
                ('bloco', models.CharField(default='x', max_length=1)),
            ],
            options={
                'db_table': 'tb_blocos',
            },
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_periodo', models.IntegerField()),
                ('nome_periodo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tb_periodos',
            },
        ),
        migrations.CreateModel(
            name='Laboratorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_sala', models.IntegerField()),
                ('capacidade', models.IntegerField()),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.blocos')),
            ],
            options={
                'db_table': 'tb_laboratorios',
            },
        ),
        migrations.CreateModel(
            name='ReservasLaboratorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField()),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.blocos')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.laboratorios')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.periodos')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.professores')),
            ],
            options={
                'db_table': 'tb_reservas_laboratorios',
            },
        ),
    ]
