# Generated by Django 5.0.7 on 2024-07-31 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reservaslaboratorios_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservaslaboratorios',
            old_name='id',
            new_name='id_reserva',
        ),
    ]
