# Generated by Django 5.0.7 on 2024-07-31 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_rename_id_reservaslaboratorios_id_reserva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservaslaboratorios',
            old_name='id_reserva',
            new_name='id',
        ),
    ]
